/**
 * @file category.model.ts
 * @description Data model and default presets for Expense Categories.
 * Designed for easy customization in open-source deployments.
 */

export interface Category {
  /** Unique primary key auto-generated by IndexedDB */
  id?: number;
  
  /** Category display name (e.g., 'Food & Dining', 'Housing') */
  name: string;

  /** Material Design Icon name (e.g., 'fastfood', 'home', 'directions_car') */
  icon: string;

  /** HEX color code associated with the category badge/chart */
  color: string;

  /** Flag indicating whether this is a system default or user-created category */
  isDefault?: boolean;

  /** Optional monthly budget threshold for this category */
  budgetLimit?: number;
}

/**
 * Pre-populated default categories for initial database seeding.
 * Open-source contributors can modify or add initial categories here.
 */
export const DEFAULT_CATEGORIES: Omit<Category, 'id'>[] = [
  { name: 'Food & Dining', icon: 'restaurant', color: '#ff6b6b', isDefault: true },
  { name: 'Housing & Rent', icon: 'home', color: '#4ecdc4', isDefault: true },
  { name: 'Transportation', icon: 'directions_car', color: '#ffe66d', isDefault: true },
  { name: 'Utilities & Bills', icon: 'bolt', color: '#1a535c', isDefault: true },
  { name: 'Entertainment', icon: 'movie', color: '#9b5de5', isDefault: true },
  { name: 'Shopping', icon: 'shopping_bag', color: '#f15bb5', isDefault: true },
  { name: 'Health & Fitness', icon: 'favorite', color: '#00bbf9', isDefault: true },
  { name: 'Salary & Income', icon: 'account_balance_wallet', color: '#00f5d4', isDefault: true },
  { name: 'Miscellaneous', icon: 'category', color: '#6c757d', isDefault: true }
];
