/**
 * @file build-info.ts
 * @description Build-time stamped version and metadata.
 *
 * AUTO-GENERATED by scripts/set-build-date.js — do NOT edit manually.
 * This file is updated automatically before every `pnpm run build`.
 */

export interface BuildInfo {
  appVersion: string;
  gitBranch: string;
  commitHash: string;
  /** Static date string set at build time — does NOT change on page reload */
  lastBuildDate: string;
}

export const BUILD_INFO: BuildInfo = {
  appVersion: 'v0.2.0',
  gitBranch: 'main',
  commitHash: 'c19cd6c',
  lastBuildDate: '2 Aug 2026, 10:24 am',
};
