/**
 * @file build-info.ts
 * @description Build-time stamped version and metadata.
 *
 * AUTO-GENERATED by scripts/set-build-date.js — do NOT edit manually.
 * This file is updated automatically before every `pnpm run build`.
 */

export interface BuildInfo {
  appVersion: string;
  gitBranch: string;
  commitHash: string;
  /** Static date string set at build time — does NOT change on page reload */
  lastBuildDate: string;
}

export const BUILD_INFO: BuildInfo = {
  appVersion: 'v0.3.1',
  gitBranch: 'dev',
  commitHash: 'c19623a',
  lastBuildDate: '3 Aug 2026, 06:17 pm',
};
